title: Nicolas Mattis (PhD @VU Amsterdam)
author:
  name: Nicolas Mattis
  email: n.m.mattis@vu.nl
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: classic.scss 
    
  header_pages:
   - about.md
   - publications.md
  
  include: 
    footer.html
  
  # social links
  twitter_username: MattisNicolas
  github_username:  nickma101
  linkedin: nicolas-mattis-41464a106
  
# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
