theme: jekyll-theme-tactile

title: Nicolas Mattis (PhD@VU)
author: Nicolas Mattis
email: n.m.mattis@vu.nl



description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
# social links
twitter_username: MattisNicolas
github_username:  nickma101

show_excerpts: true # set to false to remove excerpts on the homepage
