title: Nicolas Mattis (PhD @VU Amsterdam)
author:
  name: Nicolas Mattis
  email: n.m.mattis@vu.nl
description: > # this means to ignore newlines until "show_excerpts:"
  Interested in diversity-aware newsrecommender design or computational communication science more broadly? Feel free to reach out and defintely check out some of the awesome research that is going on at CCS Amsterdam.

show_excerpts: true # set to false to hide excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark.scss 
    
  header_pages:
   - about.md
   - publications.md
   - conferences_and_talks.md
#   - teaching.md
#   - blog.md
  
  social_links:
    twitter: MattisNicolas
    github:  nickma101
    linkedin: nicolas-mattis-41464a106
  
# Build settings
# theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
